--- #YAML:1.0
name:                Test-Harness
version:             2.65_01
abstract:            ~
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              ~
distribution_type:   module
requires:     
    File::Spec:                    0.6
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
